"""Initial schema

Revision ID: 38dba3581548
Revises: 
Create Date: 2025-11-20 15:01:17.786742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38dba3581548'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_items',
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('subtopic', sa.String(length=200), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('content_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('content_id')
    )
    op.create_index(op.f('ix_content_items_content_id'), 'content_items', ['content_id'], unique=False)
    op.create_index(op.f('ix_content_items_difficulty_level'), 'content_items', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_content_items_format'), 'content_items', ['format'], unique=False)
    op.create_index(op.f('ix_content_items_subtopic'), 'content_items', ['subtopic'], unique=False)
    op.create_index(op.f('ix_content_items_topic'), 'content_items', ['topic'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dialogs',
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dialog_type', sa.String(length=50), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dialog_id')
    )
    op.create_index(op.f('ix_dialogs_dialog_id'), 'dialogs', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_dialogs_user_id'), 'dialogs', ['user_id'], unique=False)
    op.create_table('experiments',
    sa.Column('experiment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('experiment_name', sa.String(length=100), nullable=False),
    sa.Column('variant_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('ended_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experiment_id')
    )
    op.create_index('idx_experiments_name', 'experiments', ['experiment_name'], unique=False)
    op.create_index('idx_experiments_user_id', 'experiments', ['user_id'], unique=False)
    op.create_index('idx_experiments_variant', 'experiments', ['variant_name'], unique=False)
    op.create_table('user_profiles',
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_mastery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferred_format', sa.String(length=20), nullable=True),
    sa.Column('learning_pace', sa.String(length=20), nullable=True),
    sa.Column('error_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_response_time', sa.Float(), nullable=True),
    sa.Column('avg_accuracy', sa.Float(), nullable=True),
    sa.Column('total_interactions', sa.Integer(), nullable=True),
    sa.Column('total_time_spent', sa.Float(), nullable=True),
    sa.Column('current_difficulty', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_user_profiles_profile_id'), 'user_profiles', ['profile_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=False),
    sa.Column('sender_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_question', sa.Boolean(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.dialog_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_messages_dialog_id'), 'messages', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    op.create_table('metrics',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('dialog_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value_f', sa.Float(), nullable=True),
    sa.Column('metric_value_s', sa.String(length=255), nullable=True),
    sa.Column('metric_value_j', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['dialog_id'], ['dialogs.dialog_id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.message_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_metrics_dialog_id'), 'metrics', ['dialog_id'], unique=False)
    op.create_index(op.f('ix_metrics_message_id'), 'metrics', ['message_id'], unique=False)
    op.create_index(op.f('ix_metrics_metric_id'), 'metrics', ['metric_id'], unique=False)
    op.create_index(op.f('ix_metrics_metric_name'), 'metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_metrics_user_id'), 'metrics', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_user_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_name'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_message_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_dialog_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_dialog_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_profile_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('idx_experiments_variant', table_name='experiments')
    op.drop_index('idx_experiments_user_id', table_name='experiments')
    op.drop_index('idx_experiments_name', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_dialogs_user_id'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_dialog_id'), table_name='dialogs')
    op.drop_table('dialogs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_content_items_topic'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_subtopic'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_format'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_difficulty_level'), table_name='content_items')
    op.drop_index(op.f('ix_content_items_content_id'), table_name='content_items')
    op.drop_table('content_items')
    # ### end Alembic commands ###
