"""Full update schemas add indexes, sync with db

Revision ID: c75a200a389b
Revises: 38dba3581548
Create Date: 2025-11-21 08:27:02.411636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c75a200a389b'
down_revision: Union[str, None] = '38dba3581548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_content_prerequisites', 'content_items', ['prerequisites'], unique=False, postgresql_using='gin')
    op.create_index('idx_content_skills', 'content_items', ['skills'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_content_items_content_type'), 'content_items', ['content_type'], unique=False)
    op.create_index(op.f('ix_dialogs_dialog_type'), 'dialogs', ['dialog_type'], unique=False)
    op.create_index(op.f('ix_dialogs_started_at'), 'dialogs', ['started_at'], unique=False)
    op.create_index(op.f('ix_dialogs_topic'), 'dialogs', ['topic'], unique=False)
    op.create_index(op.f('ix_messages_sender_type'), 'messages', ['sender_type'], unique=False)
    op.create_index('idx_metrics_user_name', 'metrics', ['user_id', 'metric_name'], unique=False)
    op.create_index('idx_user_profiles_mastery', 'user_profiles', ['topic_mastery'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_profiles_mastery', table_name='user_profiles', postgresql_using='gin')
    op.drop_index('idx_metrics_user_name', table_name='metrics')
    op.drop_index(op.f('ix_messages_sender_type'), table_name='messages')
    op.drop_index(op.f('ix_dialogs_topic'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_started_at'), table_name='dialogs')
    op.drop_index(op.f('ix_dialogs_dialog_type'), table_name='dialogs')
    op.drop_index(op.f('ix_content_items_content_type'), table_name='content_items')
    op.drop_index('idx_content_skills', table_name='content_items', postgresql_using='gin')
    op.drop_index('idx_content_prerequisites', table_name='content_items', postgresql_using='gin')
    # ### end Alembic commands ###
